### ISSUE TITLE
Spaces in folder name

### ISSUE THREAD

**Issue by my2b** [Deylo/FolderHierarchy#1]
When I create new folder, I can add multiple spaces between symbols and all of them will be added into the folder name. Also, I can write folder name with spaces on the start or on the end. They will be added too.
And finally, I can use some combination of this cases to create folders with almost identical names: I have created folders with names `1.1` and `___1.1___` (replace `_` on ` `) on the same level successfuly. But I have repeated this trick only with names, which wasn't on the file manager by default.

**Comment by Deylo** [comment]
fixed
